#!/usr/bin/env python3
"""
Debug de l'état de la playlist dans l'application réelle
"""

print("🔍 INSTRUCTIONS POUR DÉBUGGER VOTRE PLAYLIST")
print("="*60)

print("\n📋 ÉTAPES À SUIVRE DANS VOTRE APPLICATION :")
print("1. Lancez votre application musicale")
print("2. Allez dans l'onglet 'Recherche'")
print("3. Ouvrez la console Python (si disponible) ou ajoutez ces lignes temporairement")
print("4. Copiez-collez ces commandes une par une :")

print("\n🔍 COMMANDES DE DEBUG À EXÉCUTER :")
print("```python")
print("# Vérifier l'état de la playlist")
print("print(f'Nombre de musiques dans main_playlist: {len(getattr(self, \"main_playlist\", []))}')") 
print("print(f'Playlist: {getattr(self, \"main_playlist\", [])[:3]}...')  # Afficher les 3 premières")
print("")
print("# Vérifier l'état du container")
print("if hasattr(self, 'playlist_container'):")
print("    children = self.playlist_container.winfo_children()")
print("    print(f'Nombre d\\'éléments affichés: {len(children)}')")
print("    print(f'Container existe: {self.playlist_container.winfo_exists()}')")
print("else:")
print("    print('playlist_container n\\'existe pas')")
print("")
print("# Vérifier la région de scroll")
print("if hasattr(self, 'playlist_canvas'):")
print("    region = self.playlist_canvas.cget('scrollregion')")
print("    print(f'Région de scroll: {region}')")
print("else:")
print("    print('playlist_canvas n\\'existe pas')")
print("")
print("# FORCER L'AFFICHAGE DE LA PLAYLIST")
print("if hasattr(self, '_display_main_playlist'):")
print("    print('Forçage de l\\'affichage de la playlist...')")
print("    self._display_main_playlist()")
print("    print('Affichage forcé terminé')")
print("else:")
print("    print('Fonction _display_main_playlist non disponible')")
print("```")

print("\n📊 RÉSULTATS ATTENDUS :")
print("• Si main_playlist est vide → Ajoutez des musiques d'abord")
print("• Si container a 0 enfants → La playlist n'est pas affichée")
print("• Si région = '0 0 1 1' → Région de scroll incorrecte")
print("• Après _display_main_playlist() → Tout devrait être corrigé")

print("\n🔧 SOLUTION ALTERNATIVE :")
print("Si vous ne pouvez pas exécuter ces commandes, ajoutez temporairement")
print("cette ligne dans votre code (par exemple dans setup_search_tab()) :")
print("")
print("```python")
print("# À ajouter temporairement dans setup_search_tab() ou similaire")
print("self.root.after(2000, lambda: self._display_main_playlist() if hasattr(self, '_display_main_playlist') else None)")
print("```")

print("\n🎯 OBJECTIF :")
print("Identifier pourquoi la playlist n'est pas affichée et forcer son affichage")

print(f"\n{'='*60}")
print("📋 EXÉCUTEZ CES COMMANDES ET RAPPORTEZ LES RÉSULTATS")
print(f"{'='*60}")